apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-npm-cache
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
